name = "presenter-selections"
main = "src/index.js"
compatibility_date = "2026-08-14"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = [ "/api/*" ]

[[kv_namespaces]]
binding = "SELECTIONS_KV"
id = "c86c20ab1b024ce6800bff046efde8d6" # trackside-apps

[vars]
VIZ_SHOW_ID = "{B1DE8A36-7CE9-45B5-B276-4868D8073937}"
VIZ_MASTER_TEMPLATE = "LF_SELECTS"
VIZ_CREATOR_VERSION = "3.2.4 (Build 24895)"
